version: '3'
services:
  fluentd:
    build: ./fluentd
    network_mode: bridge
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enrollment.enabled=true"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    network_mode: bridge
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    network_mode: bridge
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:5601 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  #zipkin:
  #  links:
  #    - "elasticsearch"
  #  environment:
  #    - STORAGE_TYPE=elasticsearch
  #    - ES_HOSTS=elasticsearch:9200
  #    # Uncomment to see requests to and from elasticsearch
  #    - ES_HTTP_LOGGING=BODY
volumes:
  elasticsearch_data:

#networks:
#  default:
#    external:
#      name: swa