version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.6.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  #zipkin:
  #  links:
  #    - "elasticsearch"
  #  environment:
  #    - STORAGE_TYPE=elasticsearch
  #    - ES_HOSTS=elasticsearch:9200
  #    # Uncomment to see requests to and from elasticsearch
  #    - ES_HTTP_LOGGING=BODY
volumes:
  elasticsearch_data:

networks:
  default:
    external:
      name: swa