version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.6.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  apm:
    image: docker.elastic.co/apm/apm-server:7.6.0
    links:
      - "elasticsearch"
      - "kibana"
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=['http://elasticsearch:9200']
      - apm-server.host="0.0.0.0:8200"
      - apm-server.secret_token="xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
      - setup.kibana.host="kibana:5601"
      - setup.template.enabled=true
      - logging.to_files=false
    depends_on:
      - "elasticsearch"
      - "kibana"

  #zipkin:
  #  links:
  #    - "elasticsearch"
  #  environment:
  #    - STORAGE_TYPE=elasticsearch
  #    - ES_HOSTS=elasticsearch:9200
  #    # Uncomment to see requests to and from elasticsearch
  #    - ES_HTTP_LOGGING=BODY
volumes:
  elasticsearch_data:

#networks:
#  default:
#    external:
#      name: swa